### ISSUE TITLE
Taxi Spawn error

### ISSUE THREAD

**Issue by Pega86** [ESX-Org/esx_taxijob#11] opened 2017-10-13 16:52 UTC
I have a problem when it spawns the taxi crash server and gives me console errors

I have set Config.EnablePlayerManagement to true and
Config.EnableSocietyOwnedVehicles = true to vehicleshop

my version essential 5.0

Error running call reference function for resource esx_society: server/main.lua:363: attempt to index a nil value (local 'store')
stack traceback:
        server/main.lua:363: in local 'ref'
        citizen:/scripting/lua/scheduler.lua:317: in function <citizen:/scripting/lua/scheduler.lua:308>
        [C]: in upvalue '_in'
        citizen:/scripting/lua/natives_server.lua:243: in function 'TriggerEventInternal'
        (...tail calls...)
        server/main.lua:362: in local 'ref'
        citizen:/scripting/lua/scheduler.lua:317: in function <citizen:/scripting/lua/scheduler.lua:308>
Error running system event handling function for resource esx_datastore: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:378: in local 'cb'
        server/main.lua:106: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>

This and my server.cfg

# you probably don't want to change these!
# only change them if you're using a server with multiple network interfaces
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

start mapmanager
start chat
start spawnmanager
start sessionmanager
start hardcap
start rconlog
start scoreboard

sv_scriptHookAllowed 1

# change this
#rcon_password yay

sv_hostname "Test!"

# nested configs!
#exec server_internal.cfg

# mysql-async config  
set mysql_connection_string "server=localhost;database=essentialmode;userid=root;password=******"

# Disable Couchdb from essentialmode
set es_enableCustomData 1

######################### Gamemode
start fivem

######################### Libs
start mysql-async

######################### Plugins

start async

# ES Base
start essentialmode
start esplugin_mysql
start es_admin2
start es_extended
start FMODT

######################### ESX Script

start cron
start esx_addonaccount
start esx_addoninventory
start esx_service
start esx_society
start esx_vehicleshop
start esx_billing
start esx_ambulancejob
start esx_bankerjob
start esx_mecanojob
start esx_taxijob
start esx_policejob
start esx_animations
start esx_atm
start esx_barbershop
start esx_basicneeds
start esx_boilerplate
start esx_clotheshop
start esx_datastore
start esx_dmvschool
start esx_drugs
start esx_garage
start esx_holdup
start esx_identity
start esx_joblisting
start esx_jobs
start esx_license
start esx_lscustom
start esx_mask
start esx_menu_default
start esx_optionalneeds
start esx_phone
start esx_property
start esx_realestateagentjob
start esx_rpchat
start esx_shops
start esx_sit
start esx_skin
start esx_status
start esx_voice
start esx_weashops
start instance
start skinchanger
start esx_menu_default
start esx_menu_list
start esx_menu_dialog
#start esx_whitelist

# loading a server icon (96x96 PNG file)
#load_server_icon myLogo.png

# convars for use from script
set temp_convar "hey world!"

# disable announcing? clear out the master by uncommenting this
#sv_master1 ""

# want to only allow players authenticated with a third-party provider like Steam?
#sv_authMaxVariance 1
#sv_authMinTrust 5

# add system admins
add_ace group.admin command allow # allow all commands
add_ace group.admin command.quit deny # but don't allow quit 
##add_principal identifier.steam:110000112345678 group.admin # add the admin to the group

# hide player endpoints in external log output
#sv_endpointprivacy true

# server slots limit (default to 30)
sv_maxclients 32

**Comment by funzik** [comment] 2017-12-10 18:54
I have problem when i want spawn taxi, nothing happens

**Comment by SkillDie** [comment] 2017-12-31 11:54
Modify your config.lua like this:

Config.EnableSocietyOwnedVehicles = **false**

**false not true** 

Enjoy ;)

**Comment by ElPumpo** [comment] 2018-04-30 21:38
Duplicate of #9

**Closed by ElPumpo** 2018-04-30 21:38 UTC
